services:
  mongodb:
    image: mongo
    container_name: ask-ai-mongoDb-container
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: bagga
      MONGO_INITDB_ROOT_PASSWORD: 3asfour25102212
      MONGO_INITDB_DATABASE: ask-ai-app
    networks:
      - websocket-network

  mongo-express:
    image: mongo-express
    container_name: ask-ai-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: bagga
      ME_CONFIG_MONGODB_ADMINPASSWORD: 3asfour25102212
    networks:
      - websocket-network
    depends_on:
      - mongodb

  redis:
    image: redis:7.0-alpine
    container_name: redis_cache_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - websocket-network


volumes:
  mongo:
  redis_data:

networks:
  websocket-network:
    driver: bridge